return {
  "olimorris/codecompanion.nvim",
  dependencies = {
    "nvim-lua/plenary.nvim",
    "nvim-treesitter/nvim-treesitter",
  },
  opts = {
    -- NOTE: The log_level is in `opts.opts`
    opts = {
      log_level = "DEBUG", -- or "TRACE"
    },
  },
}

-- NOTES
-- DEPENDENCIES
-- For Copilot, also need to install copilot.vim/lua; codecompanion requires a token generated by this plugin
