return {
  "olimorris/codecompanion.nvim",
  dependencies = {
    "nvim-lua/plenary.nvim",
    "nvim-treesitter/nvim-treesitter",
  },
  opts = {
    -- NOTE: The log_level is in `opts.opts`
    opts = {
      log_level = "DEBUG", -- or "TRACE"
    },
  },
}

-- # NOTES
-- ## KEYMAPS
--
-- ### CHAT
-- Pressing ? in the chat buffer will conveniently display all of them to you.
--
-- ## DEPENDENCIES
-- For Copilot, also need to install copilot.vim/lua; codecompanion requires a token generated by this plugin
